### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by andreology**

### CODE REVIEW

**Review by skybrodowski — APPROVED** [review]
LGTM

**Comment by rvema** [comment]
@andreology please resolve the conflicts so that this can be reviewed and merged

**Review by BrittanyIstenes — CHANGES_REQUESTED** [review]
you can just delete this PR

**Comment by BrittanyIstenes** [comment]
Closing this PR since changes were not needed to the OG Contributing guide

**Pull request closed without merging**
