### PR TITLE
Update dependencies npm audit

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Updated npm audit fixes

### CODE REVIEW

**Comment by rvema** [comment]
lets hold this change until the github action for CI checks are in place. Thanks!

**Comment by naveensrinivasan** [comment]
> lets hold this change until the github action for CI checks are in place. Thanks!

Can you please let me know the reason? This shouldn't affect the CI checks.

**Comment by rvema** [comment]
@naveensrinivasan  please update the branch so that it can be merged. Thanks for the contribution.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan please update the branch so that it can be merged. Thanks for the contribution.

👍

**Review by rvema — APPROVED** [review]
lgtm

**Pull request merged**
